INSERT INTO PORTFOLIO (PROJECT_ID, PROJECT_NAME, PROJECT_DESC, PROJECT_SUMMARY, DATE_REQUESTED, DATE_REQUIRED, PROJECT_ESTIMATES, PROJECT_TYPE, CRITICAL)
VALUES ('1','Test Project-1','Test Project-1 Description','Test Project-1 Summary','2018-06-22', '2018-06-24', 3, 'Docs Management', 'Y');

INSERT INTO KEY_CONTACTS(CONTACT_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL_ID, ROLE, DEPARTMENT, PROJECT_ID)
VALUES ('1', 'Jaigopal', 'Senapati', '915674534', 'jaigopal.senapati@gmail.com', 'Full Stack Java Developer', 'Trade', '1');
INSERT INTO KEY_CONTACTS(CONTACT_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL_ID, ROLE, DEPARTMENT, PROJECT_ID)
VALUES ('2', 'Christiano', 'Ronaldo', '915674535', 'ronaldo@gmail.com', 'Football Player', 'Portugal', '1');


INSERT INTO PORTFOLIO (PROJECT_ID, PROJECT_NAME, PROJECT_DESC, PROJECT_SUMMARY, DATE_REQUESTED, DATE_REQUIRED, PROJECT_ESTIMATES, PROJECT_TYPE, CRITICAL)
VALUES ('2','Test Project-2','Test Project-2 Description','Test Project-2 Summary','2018-06-22', '2018-06-24', 5, 'Securities & Collateral', 'N');

INSERT INTO KEY_CONTACTS(CONTACT_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL_ID, ROLE, DEPARTMENT, PROJECT_ID)
VALUES ('3', 'Brindavan Krishna', 'Dasika', '915674536', 'brinda@gmail.com', 'Senior Project Manager', 'Banking', '2');
INSERT INTO KEY_CONTACTS(CONTACT_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL_ID, ROLE, DEPARTMENT, PROJECT_ID)
VALUES ('4', 'Neymar', 'Jr', '915674537', 'neymar@gmail.com', 'Football Player', 'Brazil', '2');